import { Component, computed, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { TooltipModule } from 'primeng/tooltip';
import { ButtonModule } from 'primeng/button';import { DialogModule } from 'primeng/dialog';import { InputTextModule } from 'primeng/inputtext';import { TableModule } from 'primeng/table';import { TagModule } from 'primeng/tag';
import Swal from 'sweetalert2';
import { UsersDirectoryApi } from '@core/users/users-directory.api';import { UserOption } from '@core/users/user-option.model';import { ModuleTableShellComponent } from '@shared/components/module-table-shell/module-table-shell.component';
import { License, LicensedApplication, LicensedDevice, LicenseStatus } from '../models/licensing.model';import { LicensingApi } from '../services/licensing.api';

@Component({selector:'app-licensing-licenses',imports:[ReactiveFormsModule,ButtonModule,DialogModule,InputTextModule,TableModule,TagModule,TooltipModule,ModuleTableShellComponent],templateUrl:'./licenses-page.component.html',styleUrl:'./licenses-page.component.scss'})
export class LicensesPageComponent{
  readonly records=signal<License[]>([]);readonly applications=signal<LicensedApplication[]>([]);readonly devices=signal<LicensedDevice[]>([]);readonly users=signal<UserOption[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly dialog=signal(false);readonly editing=signal<License|null>(null);readonly selectedApplication=computed(()=>this.applications().find(a=>a.id===this.form.controls.applicationId.value));readonly selectedDevice=computed(()=>this.devices().find(d=>d.id===this.form.controls.deviceId.value));form=this.buildForm();
  constructor(private readonly api:LicensingApi,private readonly usersApi:UsersDirectoryApi){this.load();}
  load(){this.loading.set(true);forkJoin({licenses:this.api.licenses(),applications:this.api.applications(),devices:this.api.devices(),users:this.usersApi.list()}).subscribe({next:v=>{this.records.set(v.licenses);this.applications.set(v.applications.filter(x=>x.status==='ACTIVE'));this.devices.set(v.devices.filter(x=>x.status!=='REVOKED'&&x.status!=='INACTIVE'));this.users.set(v.users.filter(x=>x.status==='Activo'));this.loading.set(false);},error:e=>{this.loading.set(false);void Swal.fire('Error',e.error?.detail??'No fue posible cargar licencias','error');}});}
  open(r?:License){this.editing.set(r??null);this.form=this.buildForm(r);this.dialog.set(true);}close(){this.dialog.set(false);}
  save(){if(this.form.invalid){this.form.markAllAsTouched();return;}const mode=this.selectedApplication()?.licensingMode;if(mode==='USER_DEVICE'&&!this.form.controls.userId.value){void Swal.fire('Validación','Selecciona un usuario para USER_DEVICE','warning');return;}const raw=this.form.getRawValue();const payload={...raw,userId:mode==='DEVICE_ONLY'?null:(raw.userId||null)};this.saving.set(true);const current=this.editing();const request=current?this.api.updateLicense(current.id,payload):this.api.createLicense(payload);request.subscribe({next:()=>{this.saving.set(false);this.close();this.load();},error:e=>{this.saving.set(false);void Swal.fire('Error',e.error?.detail??'No fue posible guardar','error');}});}
  action(r:License,status:LicenseStatus){this.api.changeLicenseStatus(r.id,status).subscribe({next:()=>this.load(),error:e=>void Swal.fire('Error',e.error?.detail??'No fue posible cambiar el estado','error')});}
  severity(status:LicenseStatus):'success'|'warn'|'danger'|'secondary'{return status==='ACTIVE'?'success':status==='SUSPENDED'?'warn':status==='REVOKED'?'danger':'secondary';}
  statusLabel(status:LicenseStatus):string{return {ACTIVE:'Activa',SUSPENDED:'Suspendida',REVOKED:'Revocada',EXPIRED:'Vencida'}[status];}
  operationalLabel(value:License['operationalStatus']):string{return {READY:'Lista para usar',PENDING_ENROLLMENT:'Pendiente de enrolamiento',SUSPENDED:'Suspendida',REVOKED:'Revocada',EXPIRED:'Expirada'}[value];}
  operationalSeverity(value:License['operationalStatus']):'success'|'warn'|'danger'|'secondary'{return value==='READY'?'success':value==='PENDING_ENROLLMENT'?'warn':value==='REVOKED'?'danger':'secondary';}
  private buildForm(r?:License){return new FormGroup({applicationId:new FormControl(r?.applicationId??'',{nonNullable:true,validators:[Validators.required]}),deviceId:new FormControl(r?.deviceId??'',{nonNullable:true,validators:[Validators.required]}),userId:new FormControl(r?.userId??'',{nonNullable:true}),validFrom:new FormControl(r?.validFrom??new Date().toISOString().slice(0,10),{nonNullable:true,validators:[Validators.required]}),validUntil:new FormControl(r?.validUntil??'',{nonNullable:true,validators:[Validators.required]}),status:new FormControl<LicenseStatus>(r?.status??'ACTIVE',{nonNullable:true})});}
}
